blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://kubernetes.slack.com/messages/falco
    about: Please ask and answer questions in the `#falco` channel on Kubernetes Slack
